ALTER TABLE CUSTOMER
ADD COLUMN Cust_Lname VARCHAR(100) NULL AFTER Cust_Fname;

ALTER TABLE DRIVER
ADD COLUMN Drv_Lname VARCHAR(100) NULL AFTER Drv_Fname;

UPDATE CUSTOMER
SET Cust_Lname = ''
WHERE Cust_Lname IS NULL;

UPDATE DRIVER
SET Drv_Lname = ''
WHERE Drv_Lname IS NULL;
